### PR TITLE
add demo html

### PR DESCRIPTION
**Pull request by dai-shi**
I hope it will help developers who are not familiar to ngAnimate.

### CODE REVIEW

**Comment by dai-shi** [comment]
Here you go.

**Comment by bendrucker** [comment]
Great. Please fix the HTML since you never close the `<head>` tag and the spacing is off. Move this to the top level and call it example.html. Squash everything to one commit and I'll merge it.

**Comment by dai-shi** [comment]
Thanks. Hope it's fine now.

**Comment by bendrucker** [comment]
Great, really appreciate this!

**Comment by dai-shi** [comment]
You are welcome!

**Pull request closed without merging**
